// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "github.com/alikhanturusbekov/gofermart/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// OrderProcessor is an autogenerated mock type for the OrderProcessor type
type OrderProcessor struct {
	mock.Mock
}

// Enqueue provides a mock function with given fields: task
func (_m *OrderProcessor) Enqueue(task entity.OrderProcessTask) {
	_m.Called(task)
}

// NewOrderProcessor creates a new instance of OrderProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderProcessor {
	mock := &OrderProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
