// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alikhanturusbekov/gofermart/internal/entity"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"

	uuid "github.com/google/uuid"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userID, number
func (_m *OrderRepository) Create(ctx context.Context, userID uuid.UUID, number string) (*entity.Order, error) {
	ret := _m.Called(ctx, userID, number)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*entity.Order, error)); ok {
		return rf(ctx, userID, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *entity.Order); ok {
		r0 = rf(ctx, userID, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllByUser provides a mock function with given fields: ctx, userID
func (_m *OrderRepository) GetAllByUser(ctx context.Context, userID uuid.UUID) ([]*entity.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUser")
	}

	var r0 []*entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByNumber provides a mock function with given fields: ctx, number
func (_m *OrderRepository) GetByNumber(ctx context.Context, number string) (*entity.Order, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for GetByNumber")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Order, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Order); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkOrderProcessedTx provides a mock function with given fields: ctx, tx, number, accrual
func (_m *OrderRepository) MarkOrderProcessedTx(ctx context.Context, tx *sql.Tx, number string, accrual *float64) (*entity.Order, error) {
	ret := _m.Called(ctx, tx, number, accrual)

	if len(ret) == 0 {
		panic("no return value specified for MarkOrderProcessedTx")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string, *float64) (*entity.Order, error)); ok {
		return rf(ctx, tx, number, accrual)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string, *float64) *entity.Order); ok {
		r0 = rf(ctx, tx, number, accrual)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, string, *float64) error); ok {
		r1 = rf(ctx, tx, number, accrual)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrderStatus provides a mock function with given fields: ctx, number, status
func (_m *OrderRepository) UpdateOrderStatus(ctx context.Context, number string, status entity.OrderStatus) (*entity.Order, error) {
	ret := _m.Called(ctx, number, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.OrderStatus) (*entity.Order, error)); ok {
		return rf(ctx, number, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.OrderStatus) *entity.Order); ok {
		r0 = rf(ctx, number, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entity.OrderStatus) error); ok {
		r1 = rf(ctx, number, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
