// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alikhanturusbekov/gofermart/internal/entity"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"

	uuid "github.com/google/uuid"
)

// WithdrawalRepository is an autogenerated mock type for the WithdrawalRepository type
type WithdrawalRepository struct {
	mock.Mock
}

// CreateTx provides a mock function with given fields: ctx, tx, userID, orderNumber, sum
func (_m *WithdrawalRepository) CreateTx(ctx context.Context, tx *sql.Tx, userID uuid.UUID, orderNumber string, sum float64) (*entity.Withdrawal, error) {
	ret := _m.Called(ctx, tx, userID, orderNumber, sum)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 *entity.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, uuid.UUID, string, float64) (*entity.Withdrawal, error)); ok {
		return rf(ctx, tx, userID, orderNumber, sum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, uuid.UUID, string, float64) *entity.Withdrawal); ok {
		r0 = rf(ctx, tx, userID, orderNumber, sum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, uuid.UUID, string, float64) error); ok {
		r1 = rf(ctx, tx, userID, orderNumber, sum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllByUser provides a mock function with given fields: ctx, userID
func (_m *WithdrawalRepository) GetAllByUser(ctx context.Context, userID uuid.UUID) ([]*entity.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUser")
	}

	var r0 []*entity.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWithdrawalRepository creates a new instance of WithdrawalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithdrawalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithdrawalRepository {
	mock := &WithdrawalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
